"""Optimizee databse models

Revision ID: 133ce6d0192c
Revises: f8b54cacc4f3
Create Date: 2025-02-09 19:26:43.135578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133ce6d0192c'
down_revision = 'f8b54cacc4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metering', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metering_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_metering_location_id'), ['location_id'], unique=False)

    with op.batch_alter_table('pollution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pollution_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_pollution_location_id'), ['location_id'], unique=False)

    with op.batch_alter_table('waste', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waste_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_waste_location_id'), ['location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waste_location_id'))
        batch_op.drop_index(batch_op.f('ix_waste_created_at'))

    with op.batch_alter_table('pollution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pollution_location_id'))
        batch_op.drop_index(batch_op.f('ix_pollution_created_at'))

    with op.batch_alter_table('metering', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metering_location_id'))
        batch_op.drop_index(batch_op.f('ix_metering_created_at'))

    # ### end Alembic commands ###
